### ISSUE TITLE
Rename form1

### ISSUE THREAD

**Issue by vbjay** [VBDev2Dev/Taxi-Driver-Tools#1]
Name your forms.

frmMain

frmTaxi

....

When you do so make sure in project properties the startup object is the name of your new form.

**Comment by chr1974** [comment]
Sorry, forgot that, was sitting up late that day :)

**Comment by vbjay** [comment]
If you fix this make your commit say

# 1with no space. It will close this issue

**Comment by chr1974** [comment]
Sorry, new to git. committed and fixed, closing issue.
